spin_manifest_version = "1"
authors = ["Rajat Jindal <rajatjindal83@gmail.com>"]
description = ""
name = "spin-plugin-release-bot"
trigger = { type = "http", base = "/" }
version = "0.1.1"

[variables]
gh_token = { required = true }
upstream_spin_plugins_index_repo_name = { required = false, default = "" }
upstream_spin_plugins_index_repo_owner = { required = false, default = "" }

[[component]]
id = "spin-plugin-release-bot"
source = "main.wasm"
allowed_outbound_hosts = ["https://api.github.com", "https://github.com"]
[component.trigger]
route = "/..."
[component.build]
command = "tinygo build -target=wasi -tags=purego -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
[component.config]
gh_token = "{{ gh_token }}"
upstream_spin_plugins_index_repo_name = "{{ upstream_spin_plugins_index_repo_name }}"
upstream_spin_plugins_index_repo_owner = "{{ upstream_spin_plugins_index_repo_owner }}"
