name: Test Pull Request
on: [pull_request]
jobs:
  TestPR:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: setup spin
      uses: fermyon/actions/spin/setup@v1

    - name: "Install Go"
      uses: actions/setup-go@v3
      with:
        go-version: "1.21"

    - name: "Install TinyGo"
      uses: rajatjindal/setup-actions/tinygo@v0.0.1
      with:
        version: 'v0.30.0'

    - name: Build
      run: spin build
