name: Deploy to Fermyon Cloud
on:    
  workflow_dispatch:
    inputs: {}
  push: 
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code repo
        uses: actions/checkout@v3
      
      - name: setup spin
        uses: fermyon/actions/spin/setup@v1

      - name: setup cloud plugin
        run: spin plugin install cloud --yes

      - name: "Install Go"
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"

      - name: "Install TinyGo"
        uses: rajatjindal/setup-actions/tinygo@v0.0.1
        with:
          version: 'v0.30.0'

      - name: Deploy
        uses: fermyon/actions/spin/deploy@v1
        with:
          fermyon_token: ${{ secrets.FERMYON_CLOUD_TOKEN }}
          variables: |-
            gh_token=${{ secrets.GH_TOKEN }}
